[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
exp_one = "6oTDeVZoZCjXvkPMcKnmi6Gn37rKiSSvwRUQKTENbLs8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/victor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
